version: "3.9"

services:
  backend:
    build: ./backend
    container_name: backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      DB_HOST: rollie-database.cjckiy2o8x92.us-east-2.rds.amazonaws.com
      DB_PORT: 3306
      DB_NAME: rollie
      DB_USER: root
      DB_PASSWORD: 1152225289
      PYTHON_SERVICE_URL: http://python-service:8000

  python-service:
    build: ./python-service
    container_name: python-service
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: mysql+pymysql://root:1152225289@rollie-database.cjckiy2o8x92.us-east-2.rds.amazonaws.com:3306/rollie?charset=utf8mb4&ssl_mode=REQUIRED
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8000/health"]
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 10s

  frontend:
    build:
      context: ./frontend
      args:
        REACT_APP_API_URL: http://18.217.28.151:8080
    container_name: frontend
    restart: unless-stopped
    ports:
      - "80:80"
